#!/bin/bash
#
# plan-index.sh: ~/.claude/plans 配下の各グループ (root / サブディレクトリ) に
# INDEX.md を自動生成する。plan/research ファイルの YAML frontmatter
# (status / updated / description) を読み取り、検索用の索引として出力する。
#
# 設計思想: dotfiles/claude/docs/plan-system-design.md を読んでから変更すること。
#
# 対象グループ:
#   - root: $PLANS_DIR 直下の "plan-*.md" / "feature-*.md" / "research-*.md"
#   - サブグループ: "." で始まらない第一階層サブディレクトリ (team-a, team-b 等) 直下の同上
#
# 命名規則に一致しないファイル (Claude Code native plan mode が自動保存する
# codename 命名の *.md 等) は対象外。native plan の物理的分離 (plansDirectory)
# は検証の結果機能しないため撤回済み — この命名規則フィルタが代替手段。
#
# 各グループの INDEX.md は上書き生成される。手動編集しないこと。
#
set -euo pipefail

PLANS_DIR="${PLANS_DIR:-$HOME/.claude/plans}"

if [ ! -d "$PLANS_DIR" ]; then
  echo "plan-index.sh: PLANS_DIR not found: $PLANS_DIR" >&2
  exit 0
fi

# --- frontmatter を1ファイル分読み取り、status/updated/description をタブ区切りで出力 ---
# 1行目が "---" でない、または2個目の "---" が見つからない場合は全フィールド空になる
parse_frontmatter() {
  local file="$1"
  awk '
    BEGIN { infm=0; started=0 }
    NR==1 {
      line=$0
      sub(/\r$/, "", line)
      if (line == "---") { infm=1; started=1 }
      next
    }
    infm {
      line=$0
      sub(/\r$/, "", line)
      if (line == "---") { exit }
      if (line ~ /^status:[ \t]*/) {
        v=line; sub(/^status:[ \t]*/, "", v); gsub(/^["'"'"']|["'"'"']$/, "", v); status=v
      } else if (line ~ /^updated:[ \t]*/) {
        v=line; sub(/^updated:[ \t]*/, "", v); gsub(/^["'"'"']|["'"'"']$/, "", v); updated=v
      } else if (line ~ /^description:[ \t]*/) {
        v=line; sub(/^description:[ \t]*/, "", v); gsub(/^["'"'"']|["'"'"']$/, "", v); description=v
      }
    }
    END {
      print status "\t" updated "\t" description
    }
  ' "$file"
}

# --- 1グループを処理し、$group_dir/INDEX.md を生成 ---
build_index() {
  local group_dir="$1"
  local group_name="$2"
  local index_file="$group_dir/INDEX.md"

  local files=()
  while IFS= read -r -d '' f; do
    files+=("$f")
  done < <(find "$group_dir" -maxdepth 1 -type f \( -name "plan-*.md" -o -name "feature-*.md" -o -name "research-*.md" \) -print0 2>/dev/null)

  {
    echo "# Plan Index — ${group_name} (auto-generated by plan-index.sh — do not edit)"
    echo ""

    if [ "${#files[@]}" -eq 0 ]; then
      echo "(no plans)"
    else
      local with_fm_tmp
      local no_fm_tmp
      with_fm_tmp=$(mktemp)
      no_fm_tmp=$(mktemp)

      for f in "${files[@]}"; do
        local base status updated description mtime fm_out rest
        base=$(basename "$f")
        # NOTE: 古い /bin/bash (macOS 標準 3.2系) は process substitution を
        # 大量のループで使うと FD リークで abort することがあるため、
        # ここは command substitution + パラメータ展開でパースする
        fm_out=$(parse_frontmatter "$f")
        status="${fm_out%%$'\t'*}"
        rest="${fm_out#*$'\t'}"
        updated="${rest%%$'\t'*}"
        description="${rest#*$'\t'}"
        # coreutils(GNU) stat が PATH 上位に来る環境があるため BSD stat を明示的に使う
        mtime=$(/usr/bin/stat -f "%m" "$f" 2>/dev/null || echo 0)

        if [ -n "$updated" ]; then
          [ -z "$status" ] && status="unknown"
          printf '%s\t%s\t%s\t%s\n' "$updated" "$base" "$status" "$description" >> "$with_fm_tmp"
        else
          printf '%s\t%s\n' "$mtime" "$base" >> "$no_fm_tmp"
        fi
      done

      if [ -s "$with_fm_tmp" ]; then
        sort -t $'\t' -k1,1r "$with_fm_tmp" | while IFS=$'\t' read -r updated base status description; do
          echo "- ${base} [${status}] ${updated} — ${description}"
        done
      fi

      if [ -s "$no_fm_tmp" ]; then
        sort -t $'\t' -k1,1nr "$no_fm_tmp" | while IFS=$'\t' read -r mtime base; do
          echo "- ${base} [no-frontmatter]"
        done
      fi

      rm -f "$with_fm_tmp" "$no_fm_tmp"
    fi
  } > "$index_file.tmp"
  mv "$index_file.tmp" "$index_file"
}

# --- root グループ ---
build_index "$PLANS_DIR" "root"

# --- サブグループ ("." で始まらない第一階層ディレクトリ) ---
while IFS= read -r -d '' d; do
  name=$(basename "$d")
  build_index "$d" "$name"
done < <(find "$PLANS_DIR" -mindepth 1 -maxdepth 1 -type d ! -name ".*" -print0 2>/dev/null)
